import Head from "next/head";
import { useSelector } from "react-redux";
import styles from "../styles/Home.module.css";

export default function Home() {
  const state = useSelector((state: any) => state);
  console.log(state.main);
  return (
    <div className={styles.container}>
      <Head>
        <title>Wellcome to my page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
