import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useDispatch } from "react-redux";
import { setTokenValue } from "../redux/slices/token.slice";
import { useEffect } from "react";

export default function Home() {
  const dispatch = useDispatch();
  useEffect(() => {
    const token = localStorage.getItem("token");
    if (token) {
      dispatch(setTokenValue(token));
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Wellcome to my page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl font-bold underline">test</div>
    </div>
  );
}
